run:
  timeout: 10m
  skip-dirs:
    - ui
    - clickhouse-operator

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    # - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    - gocognit
    - gocritic
    # - gocyclo
    # - godot
    - goerr113
    - gofmt
    # - gofumpt
    - goheader
    # - goimports
    - golint
    # - gomoddirectives 
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    # - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    # - wrapcheck
