
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/bionic64"
  #Ubuntu 18.04
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 8081, host: 8080
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "4096"
    end

  config.vm.provision "shell", inline: <<-SHELL
  #!/bin/bash
  # Update apt and get dependencies
  sudo apt-get -y update
  sudo apt-mark hold grub 
  sudo apt-mark hold grub-pc
  sudo apt-get -y upgrade
  sudo apt-get install -y zip unzip curl wget socat ebtables git vim 
  # install k0s on vagrant user
  curl -sSLf https://get.k0s.sh | sudo sh
  echo "export PATH=\$PATH:/usr/local/bin" | sudo tee -a /etc/profile
  sudo k0s install controller --enable-worker
  sleep 30 && sudo k0s start
  sudo systemctl enable k0scontroller
  sudo k0s status
  sudo k0s kubectl get nodes
  mkdir ~/.kube
  sudo cp /var/lib/k0s/pki/admin.conf ~/.kube/config
  sudo chmod -R 755 ~/.kube
  SHELL
end